### ISSUE TITLE
Add usage to enable pcntl functions

### ISSUE THREAD

**Issue by tobegit3hub** [markus-perl/php-strace#1]
I'm using Ubuntu and the usage doesn't work for me.

```
➜  php-strace-0.3  sudo ./php-strace       
php-strace 0.3 by Markus Perl (http://www.github.com/markus-perl/php-strace)

The following Requirements did not met:
PCNTL extension not found. Please install PHP PCNTL extension.
Requirements not met
➜  php-strace-0.3  php -m | grep pcntl     
pcntl
```

Later I figure it out to comment out the configuration in `php.ini`. Please add this in readme or usage.

```
;disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_ge\
t_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
```

**Comment by tobegit3hub** [comment]
I have to say this is a nice tool to improve the quality of our lives :smiley:

**Comment by markus-perl** [comment]
Hi Tobi, thank you for your feedback :-)

I don't know, why the ubuntu package maintainers decided to disable this pcntl functions, maybe for some security reasons. 

I can add a hint if pcntl is not enabled to also check the php.ini file for disabled functions with the next php-strace version.

Cheers,
Markus

**Comment by tobegit3hub** [comment]
Thanks @markus-perl and it's good enough :+1:
