### ISSUE TITLE
no time logged in output?

### ISSUE THREAD

**Issue by Reiner030** [markus-perl/php-strace#2]
Hi,

nice tool - since php-fpm didn't trace died processes as expected this is a nice tool for debugging. Thx.

One thing I am wondering about: there are no timestamp logged on our instances when running php-strace but I see in FileOutput.php in function notify() that you print it. Does it work for you this way?

**Comment by markus-perl** [comment]
The date/time is not printed to screen it is only logged to a file given by the --output option. Did you used the --output option?

**Comment by Reiner030** [comment]
ah ok, then it's also fine... 
Perhaps there could be within another update a small hint in readme for this / the live options
(sorry, I understood the parameter description wrongly) ?
e.g.:

```
--live                  search while running in loop for new upcoming pid's
-o|--output <string>    output log to file with timestamp
```

Bests
